-- DOMINÓ DO TORRES - MySQL Schema
-- Execute no phpMyAdmin ou linha de comando

CREATE TABLE IF NOT EXISTS players (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  photo LONGTEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS matches (
  id VARCHAR(50) PRIMARY KEY,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  team_a JSON NOT NULL,
  team_b JSON NOT NULL,
  score_a INT NOT NULL,
  score_b INT NOT NULL,
  winner VARCHAR(1) NOT NULL,
  buchuda BOOLEAN DEFAULT FALSE,
  buchuda_de_re BOOLEAN DEFAULT FALSE,
  duration_sec INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
